sudo: false
language: ruby
addons:
  apt:
    packages:
      - dbus

rvm:
  - 2.5
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  - jruby-9.1.5.0
  - ruby-head
matrix:
  allow_failures:
    - rvm: jruby-9.1.5.0
    - rvm: ruby-head
env:
  global:
    - TESTOPTS=-v
    - JRUBY_OPTS="--debug"
